### ISSUE TITLE
FileType Support?

### ISSUE THREAD

**Issue by XiaotianM** [wkentaro/labelme#19] opened 2017-08-27 13:56 UTC
Hello, I have set up the Labelme. However, it seems to only support the filetype like *.b'bmp'... 
So I don‘t know how to use it. Besides, when I use your example codes, it has gone wrong. Problem presented as follows: "Error saving label data, a bytes-like object is required, not  'str' "

Can you tell me how to solve this problem? Thank you

**Comment by wkentaro** [comment] 2017-08-27 14:29
Please specify version of labelme and pyqt.

**Comment by XiaotianM** [comment] 2017-08-28 02:32
Win10 platform, Anaconda, and I install labelme by conda create --name=labelme python=3.5, and others are the same as your guidance

**Comment by wkentaro** [comment] 2017-08-29 02:10
```
conda list pyqt | grep pyqt
```

**Comment by XiaotianM** [comment] 2017-08-29 06:32
pyqt 5.6.0 py35_0
I think pyqt is OK, 
the labelme GUI is ok, but I can not load the image.

![labelme](https://user-images.githubusercontent.com/29722350/29807475-c341c2ec-8cc6-11e7-8802-8bf9dace31b8.png)

**Comment by snowballball** [comment] 2017-08-30 08:10
I can not load my image, too.

**Comment by wkentaro** [comment] 2017-09-02 05:07
Confirmed. It is caused by the difference of string betwee python2 and 3.
Will be fixed via #20.

**Closed** 2017-09-02 05:26 UTC
Labels: bug
