### ISSUE TITLE
如果原始标定的标定为负数或者大于宽高，拖动点崩溃

### ISSUE THREAD

**Issue by XiaoSuiFeng** [wkentaro/labelme#473] opened 2019-08-22 11:24 UTC
Traceback (most recent call last):
  File "/home/team/devel/labelme/labelme/widgets/canvas.py", line 221, in mouseMoveEvent
    self.boundedMoveVertex(pos)
  File "/home/team/devel/labelme/labelme/widgets/canvas.py", line 423, in boundedMoveVertex
    pos = self.intersectionPoint(point, pos)
  File "/home/team/devel/labelme/labelme/widgets/canvas.py", line 565, in intersectionPoint
    d, i, (x, y) = min(self.intersectingEdges((x1, y1), (x2, y2), points))
ValueError: min() arg is an empty sequence

**Comment by wkentaro** [comment] 2019-08-23 15:57
duplicate of https://github.com/wkentaro/labelme/issues/398

**Closed by wkentaro** 2019-08-23 15:57 UTC
