### ISSUE TITLE
labelme2coco.py combines bounding boxes of same class

### ISSUE THREAD

**Issue by sawhney-medha** [wkentaro/labelme#424] opened 2019-06-24 07:27 UTC
I had 4 instances of a class in each image and in their respective annotation.json. But after converting them to coco format to get one annotation file for the entire dataset, each image had only one instance of each class. The boxes that were close by, were combined into one large bounding box. PLease look into this

**Comment by sawhney-medha** [comment] 2019-06-24 07:30
I wanted to use my dataset for training in yolov3. So while converting from coco to yolov3, I realised this. Now, I have made a script to convert to labelme (xyxy json) to yolov3 format (xywh txt per image).

**Comment by wkentaro** [comment] 2019-06-24 14:20
This is a duplicate of https://github.com/wkentaro/labelme/issues/419. Please refer to [my response](https://github.com/wkentaro/labelme/issues/419#issuecomment-503721606) there.

**Closed by wkentaro** 2019-06-24 14:20 UTC

**Comment by JennyLouise** [comment] 2019-07-16 14:59
I commented on #419 , but thought I'd put my solution here too just in case.

> I replaced lines 109 to 125 in the original labelme2coco.py file with the following, renaming labels to person-1, person-2, etc, before adding them to the coco annotations file.
> 
> ```
>         masks = {}                                     # for area
>         segmentations = collections.defaultdict(list)  # for segmentation
>         labels_indices = {}
> 
>         for shape in label_data['shapes']:
>             points = shape['points']
>             label = shape['label']
>             shape_type = shape.get('shape_type', None)
>             mask = labelme.utils.shape_to_mask(
>                 img.shape[:2], points, shape_type
>             )
> 
>             if label in masks:
>                 labels_indices[label] += 1
>                 label=label+"-"+str(labels_indices[label])
>                 
>             else:
>                 labels_indices[label]=0
> 
>             masks[label] = mask
> ```
