### ISSUE TITLE
 assert len(items) == 1

### ISSUE THREAD

**Issue by canghaiyunfan** [wkentaro/labelme#306] opened 2019-01-28 03:08 UTC
Traceback (most recent call last):
  File "d:\python\lib\site-packages\labelme\app.py", line 1004, in newShape
    text = self.labelDialog.popUp(text)
  File "d:\python\lib\site-packages\labelme\widgets\label_dialog.py", line 141, in popUp
    assert len(items) == 1
AssertionError

**Comment by wkentaro** [comment] 2019-01-28 21:36
duplicate of https://github.com/wkentaro/labelme/issues/283

**Closed by wkentaro** 2019-01-28 21:36 UTC
Labels: more-information-needed
