### ISSUE TITLE
Different categories in different graphs correspond to the same label by labelme

### ISSUE THREAD

**Issue by joshua23333** [wkentaro/labelme#496] opened 2019-10-06 03:38 UTC
hi, Suppose there are 5 categories in the dataset, and there are three categories in one graph. We label them as 1, 2 and 3, and there are two different categories in the other graph. We can only label them as 1, 2 by labelme, however two different categories in two graphs correspond to the same label 1, it is there any solutions about that, thankyou

**Comment by Li-Xiao-Yu** [comment] 2019-10-25 08:38
@wkentaro

**Comment by wkentaro** [comment] 2019-10-25 08:43
What is "graph"..?

**Comment by Li-Xiao-Yu** [comment] 2019-10-25 09:03
I have two image, each has 2 classes, totally have 4 classes. the pixel in each label.png is 0, 1, 2.  i want the pixel for the ecah classes is 0,1,2,3,4. just like the Camvid dataset's label.

**Comment by Li-Xiao-Yu** [comment] 2019-10-25 09:07
![label_viz](https://user-images.githubusercontent.com/48083463/67558545-c3227780-f749-11e9-9929-4aadb413f4e2.png)
![label_viz](https://user-images.githubusercontent.com/48083463/67558570-d03f6680-f749-11e9-90ef-a2f4b5530f47.png)

**Comment by wkentaro** [comment] 2019-10-25 09:07
See [Semantic Segmentation Example](https://github.com/wkentaro/labelme/tree/master/examples/semantic_segmentation) instead of [Tutorial](https://github.com/wkentaro/labelme/tree/master/examples/tutorial), which is *single image example*.

**Comment by wkentaro** [comment] 2019-10-25 09:08
duplicate of https://github.com/wkentaro/labelme/issues/282

**Closed by wkentaro** 2019-10-25 09:08 UTC
Labels: question
