### ISSUE TITLE
Background label issue

### ISSUE THREAD

**Issue by YidongHuang** [wkentaro/labelme#124] opened 2018-04-11 05:18 UTC
Background label seems to be added implicitly so that it is taking up the place in our custom labels. Using labelme_json_to_dataset seems to cause this issue.

**Comment by wkentaro** [comment] 2018-04-11 05:28
Also note that `labelme_json_to_dataset` script is only for the tutorial in `example/tutorial`.
If you're creating some new dataset which may not include background label, you can use `labelme.utils.shapes_to_label` function
with custom mapping from `label_name` to `label_value`, `label_name_to_value`.
https://github.com/wkentaro/labelme/blob/master/labelme/utils.py#L133

**Comment by YidongHuang** [comment] 2018-04-11 05:37
Thanks, I did not see that note. However, I still like to explain what happened. In 2.9.0 and 2.10.4, when I created label 's' and 's2', I expected to see either 's', 's2' or 's','s2', 'background'. However, what I saw was 's', 's2' label showing in the legend, not the shape circled by 'a' would not show up in the generated label_viz.png. 

In 2.10.5, 'background' label showed up, however, it is incorrectly associated with label 's2'. 
![label_viz](https://user-images.githubusercontent.com/12519408/38598030-9ed7ad0a-3d0f-11e8-9047-1131f1c7ec1e.png)

**Comment by abunesh** [comment] 2018-04-11 06:28
hey how do i use the labelme.utils.shapes_to_label function? do i have to input the names of the json files anywhere in the code?

**Comment by wkentaro** [comment] 2018-04-11 07:04
Hmm, I can't reproduce:

![label_viz](https://user-images.githubusercontent.com/4310419/38601272-f1f8705e-3da1-11e8-830a-ca6b94bb36ac.png)

**Comment by wkentaro** [comment] 2018-04-11 07:09
> hey how do i use the labelme.utils.shapes_to_label function? do i have to input the names of the json files anywhere in the code?

See example: https://github.com/wkentaro/labelme/blob/34dc4b67146bd7982dde47b45dc9dff1bdfc9771/labelme/cli/draw_json.py#L30

**Comment by YidongHuang** [comment] 2018-04-11 07:35
Thank you anyway. I will use utils.shape_to_label from now on. It works well.

**Comment by wkentaro** [comment] 2018-04-11 08:32
@YidongHuang Could you please upload your json file to somewhere on web? I'd like to reproduce your issue.

**Comment by wkentaro** [comment] 2018-04-15 05:47
I can't reproduce this, so I am closing for now.

**Closed by wkentaro** 2018-04-15 05:47 UTC
Labels: invalid

**Comment by zhangjinjing3** [comment] 2018-06-19 01:56
I met the same problem recently，my background label was wrong. I use utils.shape_to_label, but it did not work well.
