### ISSUE TITLE
[BUG] with Conda and Python 3.6

### ISSUE THREAD

**Issue by BenSpex** [wkentaro/labelme#936] opened 2021-10-19 08:28 UTC
Hi, 

When I created a new Conda enviorment with Python=3.6 on Ubuntu 20.04 and install labelme via pip this error shows: 
```
Traceback (most recent call last):
  File "/home/ben/anaconda3/envs/labelme/bin/labelme", line 5, in <module>
    from labelme.__main__ import main
  File "/home/ben/anaconda3/envs/labelme/lib/python3.6/site-packages/labelme/__main__.py", line 14, in <module>
    from labelme.app import MainWindow
  File "/home/ben/anaconda3/envs/labelme/lib/python3.6/site-packages/labelme/app.py", line 46, in <module>
    LABEL_COLORMAP = imgviz.label_colormap(value=200)
  File "/home/ben/anaconda3/envs/labelme/lib/python3.6/site-packages/imgviz/label.py", line 40, in label_colormap
    r = np.bitwise_or.reduce(np.left_shift(bitget(i, 0), j), axis=1)
  File "/home/ben/anaconda3/envs/labelme/lib/python3.6/site-packages/imgviz/label.py", line 28, in bitget
    return np.unpackbits(byteval, bitorder="little").reshape(shape)[
TypeError: 'bitorder' is an invalid keyword argument for this function
```

Creating a conda enviorment with python=3.7 works as expected. 
Consider changing the Readme to change to 3.7?

**Comment by wkentaro** [comment] 2021-10-21 19:35
This is caused by old numpy, but will be fixed via https://github.com/wkentaro/imgviz/pull/42

**Comment by wkentaro** [comment] 2021-10-21 19:39
Now it should be fixed either `pip install -U numpy` or `pip install -U imgviz`.

**Closed as completed** 2021-10-21 19:39 UTC
